In [3]:
import tensorflow as tf

w = tf.constant([1,3,3,4,5,6], shape=(3,2))
x = tf.constant([5,6,7,8,9,1], shape=(2,3))

y =  tf.matmul(w, x)

# Tensorflow 全用 tf.global_variables_initializer() 方法对所定义的变量 进行初始化 (这点要注意)
init_opt = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_opt)
    print (y.eval())

[[29 33 10]
 [47 54 25]
 [73 84 41]]


In [41]:
print tf.zeros((3,2), tf.int32)

print tf.ones((3,2), tf.int32)

print tf.random_normal(shape=(3,2), mean=-1, stddev=4)

print tf.linspace(10.0, 20.0, 2, name="linespace")

a = tf.random_shuffle(tf.constant([2,3,4,5,6,7], shape=(3,2)))

Tensor("zeros_16:0", shape=(3, 2), dtype=int32)
Tensor("ones_12:0", shape=(3, 2), dtype=int32)
Tensor("random_normal_9:0", shape=(3, 2), dtype=float32)
Tensor("linespace_6:0", shape=(2,), dtype=float32)


In [37]:
a = tf.Variable(0)
new_value = tf.add(a, tf.constant(1))
update = tf.assign(a, new_value)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(3):
        sess.run(new_value)
        sess.run(update)
        print a.eval()

1
2
3


In [45]:
# tf.train.Saver
w = tf.constant([1,3,3,4,5,6], shape=(3,2))
x = tf.constant([5,6,7,8,9,1], shape=(2,3))

y =  tf.matmul(w, x)
saver = tf.train.Saver()
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    sess.run(y)
    
    
    save_path = saver.save(sess, './Test/')
    print save_path

./Test/


In [49]:
import numpy as np

a = np.ones((3,3))
b = tf.convert_to_tensor(a)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print sess.run(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Tensorflow placeholder 占位符

In [57]:
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)

output = tf.multiply(input1, input2)

with tf.Session() as sess:
    print sess.run(output, feed_dict={input1:2.0, input2:3.9})

7.8
